In [1]:
import pickle
import re
import os
from vectorizer import vect

clf = pickle.load(open(os.path.join('pkl_objects', 'classifier.pkl'), 'rb'))

In [2]:
import numpy as np
label = {0:'negative', 1:'positive'}

In [3]:
# Example: positive review
example = ['I love this movie']
X = vect.transform(example)
print('Prediction: %s\nProbability: %.2f%%' %\
      (label[clf.predict(X)[0]], 
       np.max(clf.predict_proba(X))*100))

Prediction: positive
Probability: 87.89%


In [4]:
clf.predict(X)

array([1])

In [5]:
clf.predict(X)[0]

1

In [6]:
clf.predict_proba(X)

array([[0.12109956, 0.87890044]])

In [7]:
label[clf.predict(X)[0]], np.max(clf.predict_proba(X))*100

('positive', 87.89004408741438)

In [8]:
# # Example: negative review
import numpy as np
label = {0:'negative', 1:'positive'}
example = ['The movie was really terrible']
X = vect.transform(example)

In [9]:
clf.predict_proba(X)

array([[0.90285168, 0.09714832]])

In [10]:
label[clf.predict(X)[0]], np.max(clf.predict_proba(X))*100

('negative', 90.28516806647302)

In [13]:
# SQLite setup
import sqlite3
import os

conn = sqlite3.connect('reviews.sqlite')
c = conn.cursor()


c.execute('CREATE TABLE review_db'\
        ' (review TEXT, sentiment INTEGER, date TEXT)')

example1 = 'I love this movie'
c.execute("INSERT INTO review_db"\
        " (review, sentiment, date) VALUES"\
        " (?, ?, DATETIME('now'))", (example1, 1))

example2 = 'I disliked this movie'
c.execute("INSERT INTO review_db"\
        " (review, sentiment, date) VALUES"\
        " (?, ?, DATETIME('now'))", (example2, 0))

conn.commit()
conn.close()

'\nc.execute(\'CREATE TABLE review_db\'        \' (review TEXT, sentiment INTEGER, date TEXT)\')\n\nexample1 = \'I love this movie\'\nc.execute("INSERT INTO review_db"        " (review, sentiment, date) VALUES"        " (?, ?, DATETIME(\'now\'))", (example1, 1))\n\nexample2 = \'I disliked this movie\'\nc.execute("INSERT INTO review_db"        " (review, sentiment, date) VALUES"        " (?, ?, DATETIME(\'now\'))", (example2, 0))\n\nconn.commit()\nconn.close()\n'

In [14]:
# Reconenct to check if the reviews have been successfuly stored
conn = sqlite3.connect('reviews.sqlite')
c = conn.cursor()
c.execute("SELECT * FROM review_db WHERE date"\
        " BETWEEN '2016-11-01 00:00:00' AND DATETIME('now')")
results = c.fetchall()
conn.close()
results

[('I love this movie', 1, '2019-03-24 04:40:32'),
 ('I disliked this movie', 0, '2019-03-24 04:40:32')]